# Generated by Django 3.0.8 on 2020-07-29 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=event.models.upload_location)),
                ('category', models.CharField(choices=[('COMP/IT', 'Computer'), ('EXTC/ETRX', 'Electrical'), ('MECH/AUTO', 'Mechanical'), ('ALL', 'All'), ('NON-TECH', 'Non-Technical')], default='All', max_length=10)),
                ('event_date', models.DateField(verbose_name='event date')),
                ('reg_to', models.DateField(verbose_name='registration to')),
                ('fee', models.PositiveIntegerField(default=0)),
                ('reg_link', models.URLField()),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
