# Generated by Django 3.1 on 2020-08-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200812_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
