# Generated by Django 3.1 on 2020-08-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventpost_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
