# Generated by Django 3.1 on 2020-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200813_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='premium_applied',
            field=models.CharField(default='NO', max_length=30),
        ),
    ]
