# Generated by Django 3.1 on 2020-08-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200813_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='premium_aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='premium_applied',
            field=models.CharField(default='No', max_length=30),
        ),
    ]
