# Generated by Django 3.1 on 2020-08-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20200813_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
