# Generated by Django 3.0.8 on 2020-08-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
