# Generated by Django 3.1 on 2020-08-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200829_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='from_pce',
        ),
    ]
