# Generated by Django 3.0.8 on 2020-08-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200804_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('COMP/IT', 'Computer'), ('EXTC/ETRX', 'Electrical'), ('MECH/AUTO', 'Mechanical'), ('ALL', 'All'), ('NON-TECH', 'Non-Technical')], default='All', max_length=10),
        ),
    ]
