# Generated by Django 3.1 on 2020-08-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='related_event',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
