# Generated by Django 3.0.8 on 2020-08-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('COMP/IT', 'Computer'), ('EXTC/ETRX', 'Electrical'), ('MECH/AUTO', 'Mechanical'), ('ALL', 'All'), ('NON-TECH', 'Non-Technical')], default='ALL', max_length=10),
        ),
    ]
