# Generated by Django 3.1 on 2020-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200817_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='related_event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
