# Generated by Django 3.1 on 2020-08-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200818_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='related_event',
        ),
    ]
