# Generated by Django 3.1 on 2020-09-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_related_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
