# Generated by Django 3.0.8 on 2020-08-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='back_image',
            new_name='wallpaper',
        ),
    ]
