# Generated by Django 3.0.8 on 2020-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200731_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='category2',
            field=models.CharField(choices=[('COMP/IT', 'Computer'), ('EXTC/ETRX', 'Electrical'), ('MECH/AUTO', 'Mechanical'), ('ALL', 'All'), ('NON-TECH', 'Non-Technical'), ('nil', 'nil')], default='nil', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='category',
            field=models.CharField(choices=[('COMP/IT', 'Computer'), ('EXTC/ETRX', 'Electrical'), ('MECH/AUTO', 'Mechanical'), ('ALL', 'All'), ('NON-TECH', 'Non-Technical'), ('nil', 'nil')], default='All', max_length=10),
        ),
    ]
