# Generated by Django 3.1 on 2020-08-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventpost_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='premium',
            new_name='premium_applied',
        ),
    ]
