# Generated by Django 3.0.8 on 2020-08-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200802_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_published'),
        ),
    ]
