# Generated by Django 3.1 on 2020-08-17 16:03

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20200816_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.upload_location),
        ),
    ]
