# Generated by Django 3.1 on 2020-08-20 18:02

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20200820_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pic.png', null=True, upload_to=event.models.profile_location),
        ),
    ]
