# Generated by Django 3.1 on 2020-09-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_eventpost_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='body',
            field=models.TextField(max_length=1200),
        ),
    ]
