# Generated by Django 3.1 on 2020-09-11 23:24

from django.db import migrations, models
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=personal.models.upload_location)),
                ('url', models.URLField()),
            ],
        ),
    ]
